title: Brad Barrish's Documentation
email: brad@bradbarrish.com
description: When I want to document things publicly, this is where I do it
url: "https://docs.bradbarrish.com/"
twitter: bradbarrish

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed